name: Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "**.md"
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - "**.md"
      - ".github/workflows/**"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "14"
      - name: Install  deps
        run: |
          npm install -g markdown-toc
      - name: Prettier check
        run: |
          # if you encounter error, rerun the command below and commit the changes
          make toc
          make lint
          git diff --exit-code
